services:
  postgres:
    image: postgres:latest
    container_name: ong-pet-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ong_db

